name = "cloud-mail"
main = "src/index.js"
compatibility_date = "2025-06-04"
keep_vars = true

[observability]
enabled = true

[[d1_databases]]
binding = "db"
database_name = "cloud-mail" # 数据库的名称
database_id = "${D1_DATABASE_ID}" # 保持占位符不变

[[kv_namespaces]]
binding = "kv"
id = "${KV_NAMESPACE_ID}" # 保持占位符不变

# ==================== 唯独把 R2 这一段注释掉 ====================
# [[r2_buckets]]
# binding = "r2"
# bucket_name = "${R2_BUCKET_NAME}" 
# =============================================================

[assets]
binding = "assets"		
directory = "./dist"	
not_found_handling = "single-page-application"
run_worker_first = true

[triggers]
crons = ["0 16 * * *"]	


[vars]
#orm_log = false
domain = "${DOMAIN}"				
admin = "${ADMIN}"				
jwt_secret = "${JWT_SECRET}"			
project_link = "${PROJECT_LINK}"

linuxdo_client_id = "${LINUXDO_CLIENT_ID}"
linuxdo_client_secret = "${LINUXDO_CLIENT_SECRET}"
linuxdo_callback_url = "${LINUXDO_CALLBACK_URL}"
linuxdo_switch = "${LINUXDO_SWITCH}"

# 【在这里多加一行】明确指定不使用 r2
UPLOAD_DRIVER = "local"

[build]
command = "pnpm --prefix ../mail-vue install && pnpm --prefix ../mail-vue run build"
